import { PUI_DROPDOWN_POSITIONS } from '../../internal/positioning';
import {
  PUI_DEFAULT_ITEM_HEIGHT,
  PUI_DEFAULT_MAX_PANEL_HEIGHT,
} from '../../internal/virtualization';

export const PUI_SELECT_DEFAULT_ITEM_HEIGHT = PUI_DEFAULT_ITEM_HEIGHT;
export const PUI_SELECT_DEFAULT_MAX_PANEL_HEIGHT = PUI_DEFAULT_MAX_PANEL_HEIGHT;
export const PUI_SELECT_SEARCH_DEBOUNCE_MS = 200;
export const PUI_SELECT_TYPEAHEAD_RESET_MS = 500;

export const PUI_SELECT_OVERLAY_POSITIONS = PUI_DROPDOWN_POSITIONS;
